### ISSUE TITLE
Opencart 2.2: Install & Edit This Plugin Results in Fatal Error

### ISSUE THREAD

**Issue by zuwuko** [craigchristenson/opencart-2checkout#4]
NOT COMPATIBLE WITH OPEN CART 2.2

Using opencart 2.2. When editing this plugin I get Fatal Error:
`Fatal error: Call to undefined method ControllerPaymentTwoCheckout::render() in /home/______/public_html/store/admin/controller/payment/twocheckout.php on line 145
`

That Line 145 reads:
`$this->response->setOutput($this->render());`

Tried changing that line to:
`$this->response->setOutput($this->load->view($this->template, $data));`

I still get an unusable page full of PHP NOTICES & WARNINGS.

Replacing ./admin/controller/payment/twocheckout.php `$this->data` to `$data` Loads the data properly but the Save button does not work.

Also replaced the following and now I'm able to Save.
`$this->children = array(
			'common/header',
			'common/footer'
		);`
with
`
		$data['header'] = $this->load->controller('common/header');
		$data['footer'] = $this->load->controller('common/footer');
`

**Comment by craigchristenson** [comment]
Hi zuwuko. It did a fresh install of 2.2 and it looks like the 2Checkout integration that comes bundled with 2.2 works properly so their should be no need to install this extension. Please let me know if you have any issues with the 2Checkout module that is bundled with opencart so that I can assist with fixing them.
