### ISSUE TITLE
Notice: Error: Could not load template 

### ISSUE THREAD

**Issue by jooorystore** [craigchristenson/opencart-2checkout#7]
Notice: Error: Could not load template /home/xxxx/public_html/jo/admin/view/template/payment/twocheckout_api! in /home/xxxx/public_html/jo/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 86

Version 2.1.0.1

**Comment by calebh05** [comment]
The error you're seeing is due to not removing the install folder once Open Cart has been configured. Please remove the 'install' folder and then re-log in to your OC admin panel. I was able to replicate this error by not removing the install folder myself, and after removing it was able to log in to the admin panel without further issue.

**Comment by kumaresandev** [comment]
Notice: Error: Could not load template /home2/waveform/public_html/waveformhq/order/admin/view/theme/common/header.tpl! in /home2/waveform/public_html/waveformhq/order/vqmod/vqcache/vq2-system_storage_modification_system_library_template_php.php on line 23

I have error when trying to access admin. The install folder is not in there, already deleted that...
